import os
from github import Github
from typing import List, Dict

def get_github_client():
    token = os.getenv("GITHUB_TOKEN")
    return Github(token)

def parse_repo_url(url: str):
    """Extract owner and repo name from GitHub URL"""
    # Handle: https://github.com/owner/repo or owner/repo
    url = url.strip().rstrip("/")
    if "github.com" in url:
        parts = url.split("github.com/")[-1].split("/")
    else:
        parts = url.split("/")
    return parts[0], parts[1]

def get_repo_files(repo_url: str, extensions: List[str] = [".py", ".js", ".ts", ".java"]) -> List[Dict]:
    """Fetch all code files from a GitHub repository"""
    g = get_github_client()
    owner, repo_name = parse_repo_url(repo_url)
    repo = g.get_repo(f"{owner}/{repo_name}")

    files = []
    contents = repo.get_contents("")

    while contents:
        file_content = contents.pop(0)
        if file_content.type == "dir":
            contents.extend(repo.get_contents(file_content.path))
        else:
            # Only process code files
            if any(file_content.name.endswith(ext) for ext in extensions):
                try:
                    decoded = file_content.decoded_content.decode("utf-8")
                    files.append({
                        "path": file_content.path,
                        "content": decoded,
                        "sha": file_content.sha
                    })
                except Exception:
                    pass  # skip binary or unreadable files

    return files

def create_pull_request(repo_url: str, file_path: str, fixed_code: str, original_sha: str, bug_description: str, fix_explanation: str) -> str:
    """Create a branch and PR with the fix"""
    g = get_github_client()
    owner, repo_name = parse_repo_url(repo_url)
    repo = g.get_repo(f"{owner}/{repo_name}")

    # Create a new branch
    main_branch = repo.get_branch("main")
    branch_name = f"bugfix/auto-fix-{os.urandom(4).hex()}"

    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=main_branch.commit.sha
    )

    # Commit the fix to the new branch
    repo.update_file(
        path=file_path,
        message=f"fix: auto-fix bug in {file_path}",
        content=fixed_code,
        sha=original_sha,
        branch=branch_name
    )

    # Create the PR
    pr = repo.create_pull(
        title=f"🤖 Auto Fix: {bug_description[:60]}",
        body=f"""## 🤖 Autonomous Bug Fix

**Bug Description:**
{bug_description}

**Fix Explanation:**
{fix_explanation}

---
*This PR was automatically generated by Bug Fix Agent*
""",
        head=branch_name,
        base="main"
    )

    return pr.html_url